### PR TITLE
A267 dev patch 1

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by A267-dev** [comment]
Review Please @PardusEidolon I Hope this follows your documentation standards

**Comment by A267-dev** [comment]
This Branch is now ready to be merged.

**Comment by PardusEidolon** [comment]
> Review Please @PardusEidolon I Hope this follows your documentation standards

I'm more experimenting with standards here so if you think you can improve them then I'm all ears and would love what you have to say as a collaborator.

**Review by PardusEidolon — COMMENTED** [review]
I think this still needs more context in the introduction before I push this into the main branch. Is there any way we can add an example of how a command might be used? 

eg; > tool <command> <./your/directory/here>

It might seem trivial but with most documentation In API's for example I find it difficult at times to know where things go under what context. Like an apostrophe can mean something completely different to a ditto mark for example.

What do you think?

**Comment by A267-dev** [comment]
I can agree with you on that, Personally I think merging/adding some of the Information from [c20](https://github.com/Sigmmma/c20) would be a great addition, as they have a large portion of the Editing Kit's Functions documented already.

**Comment by PardusEidolon** [comment]
If [c20](https://github.com/Sigmmma/c20), then is there a need to repeat what's already been done? Would it be better to just put in the most common commands in the H3EK workflow and refer to all the other commands in [c20](https://github.com/Sigmmma/c20) that are stale?

I'm thinking in terms of what's practical. At least a couple of commands get used a lot and more frequently when modding halo 3. I'm not entirely sure about the previous titles but what I do know is that there not backwards compatible. I would also want to write up on how lighting is done and skyboxes shortly. Commands should emerge when there is a pattern, and it becomes more frequently used in a workflow that works; then it might get more fleshed out and expanded upon rather than having to go through everysingle command in tool. 

I don't really want to duplicate here. While the team behind [c20](https://github.com/Sigmmma/c20) are focusing on every single halo title details get lost and things are slow to emerge.

**Comment by PardusEidolon** [comment]
> If [c20](https://github.com/Sigmmma/c20), then is there a need to repeat what's already been done? Would it be better to just put in the most common commands in the H3EK workflow and refer to all the other commands in [c20](https://github.com/Sigmmma/c20) that are stale?
> 
> I'm thinking in terms of what's practical. At least a couple of commands get used a lot and more frequently when modding halo 3. I'm not entirely sure about the previous titles but what I do know is that there not backwards compatible. I would also want to write up on how lighting is done and skyboxes shortly. Commands should emerge when there is a pattern, and it becomes more frequently used in a workflow that works; then it might get more fleshed out and expanded upon rather than having to go through everysingle command in tool.
> 
> I don't really want to duplicate here. While the team behind [c20](https://github.com/Sigmmma/c20) are focusing on every single halo title details get lost and things are slow to emerge.

**Pull request closed without merging**
